print("Mi nombre es Luis ALfonso Martínez Alfaro")
print("******************************************")
print("Tengo 38 Años")
print("******************************************")
print("Estudie Ingenieria en sistemas computacionales")
print("*******************************************")
print("Mi signo zodiacal es Aries")
print("********************************************")
print("Estoy empezando a programar en Python")
print("❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️")